# Generated by Django 3.0.3 on 2020-02-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bangla_newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.URLField(default='')),
                ('image', models.ImageField(default='', upload_to='b_news')),
            ],
            options={
                'verbose_name_plural': 'Bangla Newspaper',
            },
        ),
    ]
