# Generated by Django 3.0.3 on 2020-02-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='english_newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.URLField(default='')),
                ('image', models.ImageField(default='', upload_to='e_news')),
            ],
            options={
                'verbose_name_plural': 'English Newspaper',
            },
        ),
    ]
