# Generated by Django 3.0.3 on 2020-02-16 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_newsapp', '0003_job_website_magazines'),
    ]

    operations = [
        migrations.CreateModel(
            name='indian_bangla_newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.URLField(default='')),
                ('image', models.ImageField(default='', upload_to='i_b_news')),
            ],
            options={
                'verbose_name_plural': 'Indian Bangla Newspaper',
            },
        ),
        migrations.CreateModel(
            name='news_channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.URLField(default='')),
                ('image', models.ImageField(default='', upload_to='news_channel')),
            ],
            options={
                'verbose_name_plural': 'News Channel',
            },
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(default='', max_length=900)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': ' Note ',
            },
        ),
    ]
